networks:
  carveo_network:
    driver: bridge
volumes:
  certbot-etc:
  certbot-www:    

services:
  carveo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./env/.env.prod
    volumes:
      - ./env:/app/env  
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - carveo_network
     
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
     - certbot-etc:/etc/letsencrypt
     - certbot-www:/var/www/certbot
     - ./nginx/certbot/conf:/etc/letsencrypt/:rw 
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - carveo_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    volumes:
    - certbot-etc:/etc/letsencrypt
    - certbot-www:/var/www/certbot
    depends_on:
    - webserver
    command: >
      sh -c "if [ ! -d '/etc/letsencrypt/live/carveo.site' ]; then certbot certonly --webroot -w /var/www/certbot --email sanjaygupta721r@gmail.com --agree-tos --no-eff-email --force-renewal -d carveo.site www.carveo.site; fi && nginx -s reload"


