version: '3.7'

networks:
  app_network:
    driver: bridge

services:
  carveo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./env:/app/env
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app_network
     
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app_network
  certbot:
    image: certbot/certbot:latest
    volumes:
    - ./nginx/certbot/www/:/var/www/certbot/:rw
    - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
