version: '3'

networks:
  carveo_network:
    driver: bridge

services:
  carveo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./env/.env.prod
    volumes:
      - ./env:/app/env  
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - carveo_network
     
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf:/etc/letsencrypt/:rw 
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - carveo_network
  certbot:
    image: certbot/certbot:latest
    volumes:
    - ./nginx/certbot/www/:/var/www/certbot/:rw
    - ./nginx/certbot/conf/:/etc/letsencrypt/:rw 
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/certbot --email sanjaygupta07054@gmail.com --agree-tos --no-eff-email -d carveo.site -d www.carveo.site
