networks:
  carveo_network:
    driver: bridge
volumes:
  certbot-etc:
  certbot-www:    

services:
  carveo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./env/.env.prod
    volumes:
      - ./env:/app/env  
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - carveo_network
      
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
     - certbot-etc:/etc/letsencrypt
     - certbot-www:/var/www/certbot
     - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro  
     - ./nginx/conf:/etc/nginx/conf.d:ro 
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - carveo_network

  certbot:
    image: certbot/certbot:latest
    volumes:
    - certbot-etc:/etc/letsencrypt
    - certbot-www:/var/www/certbot
    - ./certbot_renew.sh:/certbot_renew.sh
    command: sh -c "/app/certbot_renew.sh"


