version: '3.7'

networks:
  app_network:
    driver: bridge

services:
  carveo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app_network
