basePath: /api/v1
definitions:
  routers.HealthCheckResponse:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      error: {}
      message:
        example: Server is running and healthy
        type: string
      status:
        example: healthy
        type: string
    type: object
host: http://localhost:8090
info:
  contact:
    email: sanjaygupta07054@gmailcom
    name: Support Team
    url: https://carveo.com/support
  description: API documentation for Carevo, a car management system for tracking,
    servicing, and managing vehicles.
  termsOfService: https://carveo.com/terms
  title: Carevo Car Management API Documentation
  version: 1.0.0
paths:
  /health:
    get:
      description: Provides a simple health check to verify the server's operational
        status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routers.HealthCheckResponse'
      summary: Health Check Endpoint
      tags:
      - Health
securityDefinitions:
  CarveoAPIKey:
    description: 'JWT token required to access endpoints. Add the token in the "Authorization"
      header in the format: Bearer <JWT_TOKEN>.'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Endpoints related to car operations.
  name: Car Management
