basePath: /api/v1
host: localhost:8090
info:
  contact:
    email: support@carveo.com
    name: Support Team
    url: https://carveo.com/support
  description: API documentation for Carevo, a car management system for tracking,
    servicing, and managing vehicles.
  termsOfService: https://carveo.com/terms
  title: Carevo Car Management API Documentation
  version: 1.0.0
paths:
  /health:
    get:
      description: Check if the server is running and healthy.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health Check
      tags:
      - Health Check
securityDefinitions:
  CarveoAPIKey:
    description: 'JWT token required to access endpoints. Add the token in the "Authorization"
      header in the format: Bearer <JWT_TOKEN>.'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Endpoints related to car operations.
  name: Car Management
